version: 3
  services:
      webapp:
          build:
              context: .
              dockerfile: Dockerfile
          container_name: webapp
          restart: unless-stopped
          environment:
              APP_DEBUG: "True"
              APP_PORT: 5056
          networks:
              - backend
          ports:
              - "5056:5056"
              - "5055:5055"
          volumes:

              :/home/botcovid19/ivr/
networks:
    backend:
        driver: bridge